development:
  adapter: postgresql
  encoding: unicode
  database: cameracheck_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cameracheck_test
  pool: 5
  username: postgres
  password:
